Add client and server side mouse move action/callback
This is just a proof of concept and does not work very well. I think
the end goal would to be use to websockets instead of multiple parallel
requests, and have some sort of synchronization in the mouse movement.

Right now, on firing multiple mouse movement actions at the same time,
the following error comes up:

```
[2020-07-28 10:24:45,109] ERROR in app: Exception on /mousemove [POST]
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.8/dist-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.8/dist-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "yarc/app.py", line 49, in mousemove_callback
    pyautogui.move(delta_x, delta_y)
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 588, in wrapper
    returnVal = wrappedFunction(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 1300, in moveRel
    _mouseMoveDrag("move", None, None, xOffset, yOffset, duration, tween)
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/__init__.py", line 1489, in _mouseMoveDrag
    platformModule._moveTo(tweenX, tweenY)
  File "/usr/local/lib/python3.8/dist-packages/pyautogui/_pyautogui_x11.py", line 81, in _moveTo
    _display.sync()
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 168, in sync
    self.get_pointer_control()
  File "/usr/local/lib/python3.8/dist-packages/Xlib/display.py", line 792, in get_pointer_control
    return request.GetPointerControl(display = self.display)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/rq.py", line 1481, in __init__
    self.reply()
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/rq.py", line 1493, in reply
    self._display.send_and_recv(request = self._serial)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 556, in send_and_recv
    gotreq = self.parse_response(request)
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 643, in parse_response
    gotreq = self.parse_request_response(request) or gotreq
  File "/usr/local/lib/python3.8/dist-packages/Xlib/protocol/display.py", line 726, in parse_request_response
    raise RuntimeError("Expected reply for request %s, but got %s.  Can't happen!"
RuntimeError: Expected reply for request 34, but got 35.  Can't happen!
```

Author: return007